#!/usr/bin/env php
<?php

use Composer\Autoload\ClassLoader;
use Pnl\Application;

require_once 'runtime.php';

return fn (ClassLoader $classLoader, array $context) => new Application($classLoader, $context);
