services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pnl\App\Command\:
        resource: '../src/App/Command'

    Pnl\App\Command\HelpCommand:
        class: 'Pnl\App\Command\HelpCommand'
        arguments:
            - '@service_container'
        tags: ['command']

    Pnl\Console\:
        resource: '../src/Console'
        exclude:
            - '../src/Console/Input'
            - '../src/Console/Output'

    Pnl\Installer\:
        resource: '../src/Installer'
        exclude:
            - '../src/Installer/RepositoryApi.php'

    Pnl\Installer\GithubApi:
        arguments:
            - 'https://api.github.com'
