name: installation test

on: [push]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: install dependencies
        run: composer install

      - name: Install test extensions
        run: ./pnl install git@github.com:Fan2Shrek/pnl-test.git

      - name: run extensions tests
        run: ./pnl pnltest test --secret=Hello_World!
